/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, {useEffect, useRef} from 'react'
import {useAnimations, useFBX, useGLTF} from '@react-three/drei'

const Avatar = ({animationName = 'idle', setAnimationName, ...props}) => {
    const group = useRef()
    const { nodes, materials } = useGLTF('/models/avatar/avatar.glb')

    // Load animation
    const idle = useFBX('/models/animations/idle.fbx')
    const bow = useFBX('/models/animations/bow.fbx')
    const nod = useFBX('/models/animations/nod.fbx')
    const code = useFBX('/models/animations/code.fbx')
    const texting = useFBX('/models/animations/texting.fbx')
    const armStretch = useFBX('/models/animations/armStretch.fbx')
    const neckStretch = useFBX('/models/animations/neckStretch.fbx')

    idle.animations[0].name = 'idle'
    bow.animations[0].name = 'bow'
    nod.animations[0].name = 'nod'
    code.animations[0].name = 'code'
    texting.animations[0].name = 'texting'
    armStretch.animations[0].name = 'armStretch'
    neckStretch.animations[0].name = 'neckStretch'


    // Bind to group
    const { actions} = useAnimations([idle.animations[0], bow.animations[0], nod.animations[0], code.animations[0], texting.animations[0], armStretch.animations[0], neckStretch.animations[0]], group)

    const prevAnimationName = useRef(animationName)
    // Play animation when ready
    useEffect(() => {
        const action = actions[animationName]

        if (action) {
            action.reset().fadeIn(0.3).play()
            const duration = action.getClip().duration * 1000
            const timeout = setTimeout(() => {
                setAnimationName('idle')
            }, duration)

            return () => {
                clearTimeout(timeout)
                action.fadeOut(0.3)
            }
        }
        prevAnimationName.current = animationName;
    }, [animationName, setAnimationName, actions])

    return (
        <group {...props} dispose={null} ref={group}>
            <primitive object={nodes.Hips} />
            <skinnedMesh
                name="EyeLeft"
                geometry={nodes.EyeLeft.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeLeft.skeleton}
                morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
            />
            <skinnedMesh
                name="EyeRight"
                geometry={nodes.EyeRight.geometry}
                material={materials.Wolf3D_Eye}
                skeleton={nodes.EyeRight.skeleton}
                morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
                morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Head"
                geometry={nodes.Wolf3D_Head.geometry}
                material={materials.Wolf3D_Skin}
                skeleton={nodes.Wolf3D_Head.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
            />
            <skinnedMesh
                name="Wolf3D_Teeth"
                geometry={nodes.Wolf3D_Teeth.geometry}
                material={materials.Wolf3D_Teeth}
                skeleton={nodes.Wolf3D_Teeth.skeleton}
                morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
                morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Hair.geometry}
                material={materials.Wolf3D_Hair}
                skeleton={nodes.Wolf3D_Hair.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Top.geometry}
                material={materials.Wolf3D_Outfit_Top}
                skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
                material={materials.Wolf3D_Outfit_Bottom}
                skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
                material={materials.Wolf3D_Outfit_Footwear}
                skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            />
            <skinnedMesh
                geometry={nodes.Wolf3D_Body.geometry}
                material={materials.Wolf3D_Body}
                skeleton={nodes.Wolf3D_Body.skeleton}
            />
        </group>
    )
}

useGLTF.preload('/models/avatar/avatar.glb')

export default Avatar